apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildbeast
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wildbeast
  template:
    metadata:
      labels:
        app: wildbeast
    spec:
      containers:
      - name: wildbeast
        image: pabloapache/jenkins-wildbeast:{{tag}}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: wildbeast
spec:
  selector:
    app: wildbeast
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
    nodePort: 30000